### ISSUE TITLE
MicroBrewer user interface recipes

### ISSUE THREAD

**Issue by drogars** [rafacost/bbs_mod#3]
I have been experimenting with this excellent mod in a small modpack that includes JEI.   JEI picked up the recipes and most of them seem to work, but I have been unable to get the following recipes to work:

- sugar and wheat => LME 3.3 lb
Expected: liquid malt extract wheat 3.3. lb
Observed: nothing happens

- sugar and malt => LME 3.3 lb
Expected: liquid malt wheat 3.3. lb
Observed: it seems to work at first, the standard progress arrow works, and then it seems to get into an infinite loop of processing and nothing ever happens

- sugar and pilsen malt => LME pilsen 3.3 lb
Expected: liquid malt pilsen 3.3 lb
Observed: it seems to work at first, the standard progress arrow works, and then it seems to get into an infinite loop of processing and nothing ever happens

I suspect many of the other sugar based recipes will not work, but I have not tested them yet.

**Comment by rafacost** [comment]
> 
> 
> I have been experimenting with this excellent mod in a small modpack that includes JEI. JEI picked up the recipes and most of them seem to work, but I have been unable to get the following recipes to work:
> 
>     * sugar and wheat => LME 3.3 lb
>       Expected: liquid malt extract wheat 3.3. lb
>       Observed: nothing happens
> 
>     * sugar and malt => LME 3.3 lb
>       Expected: liquid malt wheat 3.3. lb
>       Observed: it seems to work at first, the standard progress arrow works, and then it seems to get into an infinite loop of processing and nothing ever happens
> 
>     * sugar and pilsen malt => LME pilsen 3.3 lb
>       Expected: liquid malt pilsen 3.3 lb
>       Observed: it seems to work at first, the standard progress arrow works, and then it seems to get into an infinite loop of processing and nothing ever happens
> 
> 
> I suspect many of the other sugar based recipes will not work, but I have not tested them yet.

Hi.
Thanks for the inputs.
What happens is that I couldn't figure out if there is a way to show the required number of items in JEI.
I will do some research to see if this can be added to the next update.
All malt recipes should be created using 64 sugar and 64 malt types.
Check the mod's wiki for the malts recipe here:
[https://github.com/rafacost/bbs_mod/wiki/Malt-Recipes](https://github.com/rafacost/bbs_mod/wiki/Malt-Recipes)
Once again, thanks!
rafacost

**Comment by rafacost** [comment]
[](https://github.com/rafacost/bbs_mod/wiki/Malt-Recipes)
