### ISSUE TITLE
agricraft support

### ISSUE THREAD

**Issue by TheNimbleNinja** [rafacost/bbs_mod#8]
i was wanting to switch from the grafter recipes to a cross breeding with agricraft but your seeds cant be put into crop sticks. this makes me sad :( can you add support for agricraft?

**Comment by rafacost** [comment]
When I first started this mod I tried to make it agricraft compatible, but unfortunately couldnt find any documentation on how to do it. I would love to add it, but right now I dont have time. But feel free to fork the project and take it a shot.
